// 보안 일괄패치 PDCA Layer 2 (H12): 에러 코드 SSOT
// 모든 서비스가 동일한 코드 사용해 클라이언트 처리 일관성 확보

export const ErrorCode = {
  // 4xx
  INVALID_INPUT: "INVALID_INPUT",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  NO_REFRESH_TOKEN: "NO_REFRESH_TOKEN",
  INVALID_REFRESH: "INVALID_REFRESH",
  REFRESH_EXPIRED: "REFRESH_EXPIRED",
  REFRESH_REUSE_DETECTED: "REFRESH_REUSE_DETECTED",
  CSRF_TOKEN_INVALID: "CSRF_TOKEN_INVALID",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  TOO_MANY_ATTEMPTS: "TOO_MANY_ATTEMPTS",
  INTERNAL_TOKEN_INVALID: "INTERNAL_TOKEN_INVALID",
  INVALID_AUDIENCE: "INVALID_AUDIENCE",
  // 5xx
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
